
CREATE OR REPLACE TABLE `nc_production.20250503_scorecard_nc` AS

SELECT 37 AS STATE_FIPS
WITH county_fips_map AS (
  SELECT 'ALAMANCE' AS COUNTY_NAME, '001' AS COUNTY_FIPS UNION ALL
  SELECT 'ALEXANDER', '003' UNION ALL
  SELECT 'ALLEGHANY', '005' UNION ALL
  SELECT 'ANSON', '007' UNION ALL
  SELECT 'ASHE', '009' UNION ALL
  SELECT 'AVERY', '011' UNION ALL
  SELECT 'BEAUFORT', '013' UNION ALL
  SELECT 'BERTIE', '015' UNION ALL
  SELECT 'BLADEN', '017' UNION ALL
  SELECT 'BRUNSWICK', '019' UNION ALL
  SELECT 'BUNCOMBE', '021' UNION ALL
  SELECT 'BURKE', '023' UNION ALL
  SELECT 'CABARRUS', '025' UNION ALL
  SELECT 'CALDWELL', '027' UNION ALL
  SELECT 'CAMDEN', '029' UNION ALL
  SELECT 'CARTERET', '031' UNION ALL
  SELECT 'CASWELL', '033' UNION ALL
  SELECT 'CATAWBA', '035' UNION ALL
  SELECT 'CHATHAM', '037' UNION ALL
  SELECT 'CHEROKEE', '039' UNION ALL
  SELECT 'CHOWAN', '041' UNION ALL
  SELECT 'CLAY', '043' UNION ALL
  SELECT 'CLEVELAND', '045' UNION ALL
  SELECT 'COLUMBUS', '047' UNION ALL
  SELECT 'CRAVEN', '049' UNION ALL
  SELECT 'CUMBERLAND', '051' UNION ALL
  SELECT 'CURRITUCK', '053' UNION ALL
  SELECT 'DARE', '055' UNION ALL
  SELECT 'DAVIDSON', '057' UNION ALL
  SELECT 'DAVIE', '059' UNION ALL
  SELECT 'DUPLIN', '061' UNION ALL
  SELECT 'DURHAM', '063' UNION ALL
  SELECT 'EDGECOMBE', '065' UNION ALL
  SELECT 'FORSYTH', '067' UNION ALL
  SELECT 'FRANKLIN', '069' UNION ALL
  SELECT 'GASTON', '071' UNION ALL
  SELECT 'GATES', '073' UNION ALL
  SELECT 'GRAHAM', '075' UNION ALL
  SELECT 'GRANVILLE', '077' UNION ALL
  SELECT 'GREENE', '079' UNION ALL
  SELECT 'GUILFORD', '081' UNION ALL
  SELECT 'HALIFAX', '083' UNION ALL
  SELECT 'HARNETT', '085' UNION ALL
  SELECT 'HAYWOOD', '087' UNION ALL
  SELECT 'HENDERSON', '089' UNION ALL
  SELECT 'HERTFORD', '091' UNION ALL
  SELECT 'HOKE', '093' UNION ALL
  SELECT 'HYDE', '095' UNION ALL
  SELECT 'IREDELL', '097' UNION ALL
  SELECT 'JACKSON', '099' UNION ALL
  SELECT 'JOHNSTON', '101' UNION ALL
  SELECT 'JONES', '103' UNION ALL
  SELECT 'LEE', '105' UNION ALL
  SELECT 'LENOIR', '107' UNION ALL
  SELECT 'LINCOLN', '109' UNION ALL
  SELECT 'MCDOWELL', '111' UNION ALL
  SELECT 'MACON', '113' UNION ALL
  SELECT 'MADISON', '115' UNION ALL
  SELECT 'MARTIN', '117' UNION ALL
  SELECT 'MECKLENBURG', '119' UNION ALL
  SELECT 'MITCHELL', '121' UNION ALL
  SELECT 'MONTGOMERY', '123' UNION ALL
  SELECT 'MOORE', '125' UNION ALL
  SELECT 'NASH', '127' UNION ALL
  SELECT 'NEW HANOVER', '129' UNION ALL
  SELECT 'NORTHAMPTON', '131' UNION ALL
  SELECT 'ONSLOW', '133' UNION ALL
  SELECT 'ORANGE', '135' UNION ALL
  SELECT 'PAMLICO', '137' UNION ALL
  SELECT 'PASQUOTANK', '139' UNION ALL
  SELECT 'PENDER', '141' UNION ALL
  SELECT 'PERQUIMANS', '143' UNION ALL
  SELECT 'PERSON', '145' UNION ALL
  SELECT 'PITT', '147' UNION ALL
  SELECT 'POLK', '149' UNION ALL
  SELECT 'RANDOLPH', '151' UNION ALL
  SELECT 'RICHMOND', '153' UNION ALL
  SELECT 'ROBESON', '155' UNION ALL
  SELECT 'ROCKINGHAM', '157' UNION ALL
  SELECT 'ROWAN', '159' UNION ALL
  SELECT 'RUTHERFORD', '161' UNION ALL
  SELECT 'SAMPSON', '163' UNION ALL
  SELECT 'SCOTLAND', '165' UNION ALL
  SELECT 'STANLY', '167' UNION ALL
  SELECT 'STOKES', '169' UNION ALL
  SELECT 'SURRY', '171' UNION ALL
  SELECT 'SWAIN', '173' UNION ALL
  SELECT 'TRANSYLVANIA', '175' UNION ALL
  SELECT 'TYRRELL', '177' UNION ALL
  SELECT 'UNION', '179' UNION ALL
  SELECT 'VANCE', '181' UNION ALL
  SELECT 'WAKE', '183' UNION ALL
  SELECT 'WARREN', '185' UNION ALL
  SELECT 'WASHINGTON', '187' UNION ALL
  SELECT 'WATAUGA', '189' UNION ALL
  SELECT 'WAYNE', '191' UNION ALL
  SELECT 'WILKES', '193' UNION ALL
  SELECT 'WILSON', '195' UNION ALL
  SELECT 'YADKIN', '197' UNION ALL
  SELECT 'YANCEY', '199'
),

voters AS (
  SELECT 
    ncid AS VOTER_ID,
    voter_status_desc AS VOTER_STATUS,
    party_cd AS PARTY,
    SAFE.PARSE_DATE('%m/%d/%Y', registr_dt) AS LATEST_REGISTRATION_DATE,
    birth_year AS YEAR_OF_BIRTH,
    CASE
      WHEN gender_code = 'M' THEN 'M'
      WHEN gender_code = 'F' THEN 'F'
      ELSE 'U'
    END AS GENDER,
    county_desc AS COUNTY_NAME,
    res_city_desc AS RESIDENCE_CITY,
    state_cd AS RESIDENCE_STATE,
    zip_code AS RESIDENCE_ZIP,
    mail_city AS MAILING_CITY,
    mail_state AS MAILING_STATE,
    race_code AS RACE,
    ethnic_code AS ETHNICITY,
    municipality_desc AS MUNICIPALITY,
    cong_dist_abbrv AS CONGRESSIONAL_DISTRICT,
    nc_senate_abbrv AS NC_SENATE_DISTRICT,
    nc_house_abbrv AS NC_HOUSE_DISTRICT,
    school_dist_desc AS SCHOOL_DISTRICT_NAME
  FROM `tcc-research.nc_sources.20250305_nc_voter_registration_and_history`
  WHERE voter_status_desc IN ('ACTIVE', 'INACTIVE')
),

voter_file_county AS (
  SELECT 
    v.*,
    cf.COUNTY_FIPS,
    NULL AS SCHOOL_DISTRICT_CODE
  FROM voters v
  LEFT JOIN county_fips_map cf 
    ON TRIM(v.COUNTY_NAME) = cf.COUNTY_NAME
  WHERE v.VOTER_ID IS NOT NULL
)

-- Deduplicate: keep most recent registration
SELECT *
FROM (
  SELECT * ,
         ROW_NUMBER() OVER (PARTITION BY VOTER_ID ORDER BY LATEST_REGISTRATION_DATE DESC) AS rn
  FROM voter_file_county
)
WHERE rn = 1;



